version: '3.8'

services:
  reranker:
    build:
      context: ./py
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - QDRANT_URL=${QDRANT_URL}
      - RERANKER_URL=http://reranker:5005
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - NODE_ENV=production
    depends_on:
      reranker:
        condition: service_healthy
    restart: unless-stopped 