name: jito-mcp-search
services:
  - name: reranker
    source_dir: /py
    github:
      repo: your-username/your-repo-name
      branch: main
    run_command: python main.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 5005
    health_check:
      http_path: /health
    envs:
      - key: FLASK_ENV
        value: production
    routes:
      - path: /rerank
      - path: /health

  - name: mcp-server
    source_dir: /
    github:
      repo: your-username/your-repo-name
      branch: main
    build_command: pnpm install && pnpm build
    run_command: pnpm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: RERANKER_URL
        value: ${reranker.PRIVATE_URL}
      - key: QDRANT_URL
        value: ${QDRANT_URL}
      - key: QDRANT_API_KEY
        value: ${QDRANT_API_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
    routes:
      - path: /

# Using 3rd party Qdrant service - no database configuration needed 